### ISSUE TITLE
Create v1.0.5 Release

### ISSUE THREAD

**Issue by juliancheal** [chrisarcand/miqversions#16]
Once we (we meaning you) merge @NickLaMuro's commit https://github.com/chrisarcand/miqversions/pull/15 we should release a new build.

**Comment by chrisarcand** [comment]
You == Those two! 😄☝️ 

With a distinct lack of time to be able to hand over the reins for Homebrew too (but we should do that!), I'll throw whatever up there once a release is merged/tagged, just ping me.

**Comment by NickLaMuro** [comment]
> With a distinct lack of time to be able to hand over the reins for Homebrew too (but we should do that!)...

Should we create a GH issue for this?

**Comment by juliancheal** [comment]
> Should we create a GH issue for this?

@NickLaMuro I feel that's what Chris is saying.

**Comment by himdel** [comment]
Ping, `go get -u github.com/chrisarcand/miqversions` keeps giving me an ancient version where Ivanchuk is still 4.8, I'm guessing that's because it was never released?

**Comment by juliancheal** [comment]
@himdel it should be returning ' Ivanchuk | 5.11.z' at least it does when I run `go get`.

**Comment by himdel** [comment]
> It should

Agreed there, it **should** :)

```
himdel@thror:~$ which -a miqversions
/home/himdel/.gopath/bin/miqversions
himdel@thror:~$ rm /home/himdel/.gopath/bin/miqversions
himdel@thror:~$ go get -u github.com/chrisarcand/miqversions
himdel@thror:~$ miqversions
+----------------+------------------------------+------------+-------+------------+
|    MANAGEIQ    | CLOUDFORMS MANAGEMENT ENGINE | CLOUDFORMS | RUBY  | POSTGRESQL |
+----------------+------------------------------+------------+-------+------------+
|                | 5.1.z                        | 2.0        |       |            |
|                | 5.2.z                        | 3.0        |       |            |
| Anand          | 5.3.z                        | 3.1        |       |            |
| Botvinnik      | 5.4.z                        | 3.2        |       |            |
| Capablanca     | 5.5.z                        | 4.0        | 2.2.x | 9.4.x      |
| Darga          | 5.6.z                        | 4.1        | 2.2.x | 9.4.x      |
| Euwe           | 5.7.z                        | 4.2        | 2.3.x | 9.5.x      |
| Fine           | 5.8.z                        | 4.5        | 2.3.x | 9.5.x      |
| Gaprindashvili | 5.9.z                        | 4.6        | 2.3.x | 9.5.x      |
| Hammer         | 5.10.z                       | 4.7        | 2.4.x | 9.5.x      |
| Ivanchuk       | 5.11.z                       | 4.8        | 2.4.x | 10.x       |
+----------------+------------------------------+------------+-------+------------+
```

**Comment by himdel** [comment]
So, unless there's an extra `go get` flag to just download master, we need a release :)

(Or we need to push management to stop referring to Ivanchuk as 5.0 :))

**Comment by juliancheal** [comment]
@chrisarcand Hey Chris, what do you want to do about the homebrew builds do you want to give me access to https://github.com/chrisarcand/homebrew-formulae/blob/master/Formula/miqversions.rb or shall we create a new homebrew tap?

**Comment by chrisarcand** [comment]
@himdel Something's borked with your setup there. There's no extra flag, and `go get -u` should get you updated (it's basically just a git pull, if you're unfamiliar with Go); I just sanity checked that it works, too. 

@juliancheal Yeah, the homebrew tap there is specifically designed to be a general tap for myself (for any projects) so I'd go ahead and just make a new one and then just update the README to tap that one instead. I suggest making a github.com/manageiq/homebrew-formulae (so users can do `brew tap manageiq/formulae`)

**Comment by himdel** [comment]
Thanks @chrisarcand , no idea what, but `rm -rf .gopath/src/github.com/chrisarcand/miqversions/ ; go get -u github.com/chrisarcand/miqversions` helped. (Maybe something changed for go1.12? I'm only vaguely familiar with go, I heard about a big module change but that's about it.)
