### ISSUE TITLE
Need a new version release for Hammer

### ISSUE THREAD

**Issue by juliancheal** [chrisarcand/miqversions#8]
Version `1.0.3` is the last binary release and that only goes up to Gaprindashvili. A new version needs to be made for Hammer. 🔨

**Comment by chrisarcand** [comment]
Thanks, been lazy and forgot about it! Version 1.0.4 is tagged and a High Sierra bottle is available via Homebrew!

https://github.com/chrisarcand/miqversions/releases/tag/v1.0.4
